"""capter 11.1

Revision ID: c884e4514bfe
Revises: 8a306fbc733a
Create Date: 2017-09-28 09:43:34.804586

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c884e4514bfe'
down_revision = '8a306fbc733a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'body_html')
    # ### end Alembic commands ###
